services:

  api:
    build: .
    ports:
      - 8081:80
    volumes:
      - ./api:/var/www/html/

  database:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/0-init.sql
      - ./data.sql:/docker-entrypoint-initdb.d/1-data.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=wanderPlace
      - POSTGRES_USER=unknown

volumes:
  pgadmin-data:
  db-data: